### ISSUE TITLE
Server-Sent Events were broken by 6bbd3f4

### ISSUE THREAD

**Issue by irichter** [libetl/local-traffic#534]
When commit 6bbd3f4 rewrote `inboundResponse.write` to `(inboundResponse.write as any)` (see [index.ts:3591](https://github.com/libetl/local-traffic/blame/f54a0490b7af891da4a5793a9aa8d3c752d09be6/index.ts#L3591)), it dropped the semicolon from that line. Without that semicolon, and because the next code is wrapped in parentheses, the code tries to use the output from `inboundResponse.write(...)` as a function, which fails with `TypeError: r.write(...) is not a function`.

**Comment by libetl** [comment]
Oops thank you for reporting this.

**Comment by libetl** [comment]
should be fixed with 0.1.28 and 0.1.29
